import 'package:flutter/material.dart';
import '../services/sync_service.dart';
import '../theme/app_theme.dart';

class SyncScreen extends StatefulWidget {
  const SyncScreen({super.key});

  @override
  State<SyncScreen> createState() => _SyncScreenState();
}

class _SyncScreenState extends State<SyncScreen> {
  final TextEditingController _codeController = TextEditingController();
  bool _isLoading = false;
  String? _lastSyncedCode;
  String? _statusMessage;
  bool _isSuccess = false;

  @override
  void initState() {
    super.initState();
    _loadSyncStatus();
  }

  Future<void> _loadSyncStatus() async {
    final code = await SyncService().getLastSyncedCode();
    if (!mounted) return;
    setState(() {
      _lastSyncedCode = code;
    });
  }

  Future<void> _performSync() async {
    final code = _codeController.text.trim();
    if (code.isEmpty) {
      setState(() {
        _statusMessage = "Please enter a valid 6-digit Family Link Code (e.g. FAM-8921).";
        _isSuccess = false;
      });
      return;
    }

    setState(() {
      _isLoading = true;
      _statusMessage = null;
    });

    final syncedProfiles = await SyncService().downloadAndCacheByCode(code);

    if (!mounted) return;

    setState(() {
      _isLoading = false;
      if (syncedProfiles != null && syncedProfiles.isNotEmpty) {
        _isSuccess = true;
        _lastSyncedCode = code.toUpperCase();
        _statusMessage = "Successfully paired & synced ${syncedProfiles.length} face profiles to local disk storage!";
      } else {
        _isSuccess = false;
        _statusMessage = "Invalid code or no profiles found under code '$code'. Check caregiver dashboard.";
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppTheme.colorBackground,
      appBar: AppBar(
        title: const Text("Device Link & Local Sync"),
      ),
      body: SafeArea(
        child: SingleChildScrollView(
          padding: const EdgeInsets.all(24.0),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              // Info Card
              Card(
                child: Padding(
                  padding: const EdgeInsets.all(20.0),
                  child: Column(
                    children: [
                      const Icon(Icons.phonelink_ring_rounded, color: AppTheme.colorPrimary, size: 56),
                      const SizedBox(height: 12),
                      const Text(
                        "Anonymous Family Link Pairing",
                        style: TextStyle(
                          fontSize: 22,
                          fontWeight: FontWeight.bold,
                          color: AppTheme.colorTextPrimary,
                        ),
                        textAlign: TextAlign.center,
                      ),
                      const SizedBox(height: 8),
                      const Text(
                        "Enter the 6-digit Family Link Code generated by your caregiver to sync photos and notes directly to your local device.",
                        style: TextStyle(fontSize: 15, height: 1.4, color: AppTheme.colorTextSecondary),
                        textAlign: TextAlign.center,
                      ),
                    ],
                  ),
                ),
              ),
              const SizedBox(height: 28),

              // Code Input Field
              TextField(
                controller: _codeController,
                textCapitalization: TextCapitalization.characters,
                style: const TextStyle(fontSize: 24, fontWeight: FontWeight.bold, letterSpacing: 2),
                textAlign: TextAlign.center,
                decoration: InputDecoration(
                  labelText: "Enter 6-Digit Family Link Code",
                  hintText: "e.g. FAM-8921",
                  border: OutlineInputBorder(borderRadius: BorderRadius.circular(16)),
                  prefixIcon: const Icon(Icons.vpn_key_rounded),
                ),
              ),
              const SizedBox(height: 20),

              // Sync Button
              ElevatedButton.icon(
                onPressed: _isLoading ? null : _performSync,
                style: ElevatedButton.styleFrom(
                  minimumSize: const Size(double.infinity, 60),
                  backgroundColor: AppTheme.colorPrimary,
                ),
                icon: _isLoading
                    ? const SizedBox(
                        width: 24,
                        height: 24,
                        child: CircularProgressIndicator(color: Colors.white, strokeWidth: 2.5),
                      )
                    : const Icon(Icons.sync_rounded, size: 28),
                label: const Text(
                  "Pair & Sync Profiles",
                  style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold),
                ),
              ),
              const SizedBox(height: 24),

              // Status Banner
              if (_statusMessage != null) ...[
                Container(
                  padding: const EdgeInsets.all(16),
                  decoration: BoxDecoration(
                    color: _isSuccess
                        ? AppTheme.colorSuccessBg
                        : AppTheme.colorErrorContainer,
                    borderRadius: BorderRadius.circular(16),
                    border: Border.all(
                      color: _isSuccess ? AppTheme.colorSuccess : AppTheme.colorError,
                    ),
                  ),
                  child: Row(
                    children: [
                      Icon(
                        _isSuccess ? Icons.check_circle_rounded : Icons.error_outline_rounded,
                        color: _isSuccess ? AppTheme.colorSuccess : AppTheme.colorError,
                        size: 32,
                      ),
                      const SizedBox(width: 14),
                      Expanded(
                        child: Text(
                          _statusMessage!,
                          style: TextStyle(
                            fontSize: 15,
                            fontWeight: FontWeight.w600,
                            color: _isSuccess ? AppTheme.colorSuccess : AppTheme.colorError,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
                const SizedBox(height: 24),
              ],

              // Last Synced Info
              if (_lastSyncedCode != null) ...[
                Container(
                  padding: const EdgeInsets.all(16),
                  decoration: BoxDecoration(
                    color: AppTheme.colorCardBg,
                    borderRadius: BorderRadius.circular(16),
                    border: Border.all(color: AppTheme.colorBorderGray),
                  ),
                  child: Row(
                    children: [
                      const Icon(Icons.verified_user_outlined, color: AppTheme.colorPrimary, size: 28),
                      const SizedBox(width: 12),
                      Expanded(
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            const Text("Active Paired Code:", style: TextStyle(fontSize: 12, color: AppTheme.colorTextSecondary)),
                            const SizedBox(height: 2),
                            Text(
                              _lastSyncedCode!,
                              style: const TextStyle(
                                fontSize: 18,
                                fontWeight: FontWeight.bold,
                                color: AppTheme.colorPrimary,
                              ),
                            ),
                          ],
                        ),
                      ),
                      const Chip(
                        label: Text("Cached Offline", style: TextStyle(fontSize: 12, fontWeight: FontWeight.bold)),
                        backgroundColor: AppTheme.colorSurfaceLow,
                      ),
                    ],
                  ),
                ),
              ],
            ],
          ),
        ),
      ),
    );
  }
}
